// <auto-generated />
namespace RecipeRobber.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Almost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Almost));
        
        string IMigrationMetadata.Id
        {
            get { return "202204220139531_Almost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
